
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const NoteStatus = {
  draft: 'draft',
  scheduled: 'scheduled',
  sent: 'sent',
  failed: 'failed'
} as const

export type NoteStatus = (typeof NoteStatus)[keyof typeof NoteStatus]


export const NoteFeedback = {
  positive: 'positive',
  negative: 'negative'
} as const

export type NoteFeedback = (typeof NoteFeedback)[keyof typeof NoteFeedback]
